### ISSUE TITLE
Some players can't click the signs to join the game

### ISSUE THREAD

**Issue by RealKomander** [Butzlabben/missilewars#105]
A few people experience a bug when they try clicking a sign and then nothing happens. No messages in console, nothing.

Use my config, be the chosen one, click the sign; I have geyserMC on my server, and bedrock players have slightly better chances to get this error.

Version: paper 1.20.1, velocity 260

Config files (couldn't attach .yml here): https://drive.google.com/drive/folders/18EsekKA5fysO4JgZXk7YKEICYt_1dYCS?usp=sharing

I can send anything else you want

**Comment by daniel-naegele** [comment]
Do players only experience this bug once when clicking the sign or is the sign not working for them entirely until the next restart?
What happens when the player reconnect to the server, does the bug still exist? What if they restart their game? Which MissileWars version are you using?

**Comment by bitter-geek** [comment]
Hi, here's the info I posted on SpigotMC (different username but you'll probably recognize it):
I am using 4.5.3 but still having trouble.

The basic idea is that I don't appear to enter the lobby when I click on the sign, I just teleport back to spawn. I don't see any messages or errors in the log, I just tp back to spawn and that's it.

Here's how I set up:

1. Download MW 4.5.3 from GitHub
2. Create a new folder on my server
3. Create a plugins folder in that folder
4. Copy the MW and WorldEdit (worldedit-bukkit-7.2.15.jar) JARs to the plugins folder
5. Copy the Paper (or Spigot, same result) .jar to the root directory
6. Run Paper: java -jar paper-1.20.1-163.jar -nogui
7. The server stops because of the EULA. I edit that file, and re-run it
8. The worlds finish building, I wait a minute, then shutdown the server
9. I wait a minute again, and start the server again
10. I enter the server and give myself op
11. I place a sign (on a tree or something) with: [MissileWars] lobby0
12. I see a message that the lobby is linked
13. I right-click on the sign and get tp'd back to spawn

This is happening on a basic, old Ubuntu 18.04 server with Java 17.0.7 and a new, Debian 12 server using a Docker container and I'm pretty sure some variation of Java 17 (I can get those specifics if needed). And, again, the latest version of Spigot or Paper, doesn't matter, both do the same thing.

Occasionally, I can get into the arena, but I can't move and a message that says something like "You're not allowed to leave the arena" (not sure of the exact wording) keeps spamming on the screen. I can't get that to happen again for a screenshot.

The game was working great for a couple weeks then suddenly I can't get it to work at all. I don't know what changed; it doesn't make any sense. The only difference is it started after I tried adding the new map and missiles, but it's having trouble even when I just do the basic config like I explain above so I don't think that's related.

**Comment by bitter-geek** [comment]
@daniel-naegele Is there anything I can help with to get this figured out? I don't program in Java but I'm pretty handy with computers and I'm happy to help in any way I can. I just got the same result with the most recent version of WorldEdit (7.2.16), and Minecraft 1.20.2 (via Paper 207).

**Comment by RedstoneFuture** [comment]
> @daniel-naegele Is there anything I can help with to get this figured out? I don't program in Java but I'm pretty handy with computers and I'm happy to help in any way I can. I just got the same result with the most recent version of WorldEdit (7.2.16), and Minecraft 1.20.2 (via Paper 207).

There are unfortunately delays in the controlling of code changes (Pull-Requests), so work on existing bugs and new features is also delayed. But thanks.

**Comment by RedstoneFuture** [comment]
@bitter-geek

"... just teleport back to spawn."

Which spawn exactly? The lobby `spawn_point`, the lobby `after_game_spawn` or the plugin `fallback_spawn`?

**Comment by bitter-geek** [comment]
@RedstoneFuture Hi! That's a good question. However, when I fired the plugin back up to try and figure that out, it started working! Did you guys fix something?

**Comment by bitter-geek** [comment]
Uh... maybe I spoke too soon? I tried it again and it didn't work, although this time I tried with the "Dam" map. When I went back to spawn, I went to the lobby spawn_point.

**Comment by RealKomander** [comment]
Fixed for me with the update
