### ISSUE TITLE
Player detection problems if Fallback-Spawn is inside the Lobby-Area

### ISSUE THREAD

**Issue by pjindras** [Butzlabben/missilewars#131]
**Describe the bug**
Player is not detected in lobby, I dont know why

**To Reproduce**

1. Go to log

**Expected behavior**
Player shold be detected and game should start

https://mclo.gs/sCMlKdo

**Server Purpur 1.20.4 Java 21

Problem occures usually when player joins the game and than leaves it into lobby before the game starts.

**Comment by RedstoneFuture** [comment]
This can happen if the positions have not been set correctly (or if there are other runtime problems with the positions that have not been considered). The overview and description of the current positions can be found [here](/RedstoneFuture/missilewars/wiki/Commands-and-Permissions#location-types). Are the "Main Fallback-Spawn" and "Lobby Area" outside the lobby area?

I will soon publish a new release, with which many bugs have generally been fixed in recent months. Then you can test it again.

**Comment by pjindras** [comment]
it should be all inside the lobby area, but the player leaves the game to main server lobby (means different server), maybe this could be an issue, I will try to put fallback area outside the lobby area, the current positions are:

---
name: "lobby0"
display_name: "&eRocket Wars"
auto_load: true
world: "world"
lobby_time: 60
join_ongoing_game: false
min_size: 2
max_size: 10
team1_name: "Červení"
team1_color: "&c"
team2_name: "Zelení"
team2_color: "&a"
spawn_point:
  x: 0.03376447698343381
  "y": 68.0
  z: -38.42421991845721
  yaw: 3.1472726
  pitch: 19.64994
after_game_spawn:
  x: 0.03376447698343381
  "y": 68.0
  z: -38.42421991845721
  yaw: 3.1472726
  pitch: 19.64994
area:
  min_x: -65
  min_y: 0
  min_z: -61
  max_x: 28
  max_y: 256
  max_z: 47
map_choose_procedure: "MAPVOTING"
possible_arenas:
- "arena0"
- "arena1"


and

fallback_spawn:
  world: world
  x: 0.03376447698343381
  y: 68.0
  z: -38.42421991845721
  yaw: 3.1472726
  pitch: 19.64994

**Comment by pjindras** [comment]
I tested it, but for me it was much better, when fallback_spawn was on the same lobby, now there are many situations, when the player is placed outside the game lobby

**Comment by RedstoneFuture** [comment]
The Lobby area is a protected area where only MissileWars players (and Admins) are allowed to be. If there are players who have not yet been registered by the MissileWars plugin, this will lead to problems. The Lobby area restriction management is therefore the guarantee for stable player management during the server runtime.

This is the current concept and it makes sense for technical reasons. It also works well for me in practice. For adjustments, I would need examples of situations in which the current structure causes problems. If the "Main Fallback-Spawn" is the server spawn it should be fine for the players, in my opinion.

**Comment by RedstoneFuture** [comment]
Or which case is the reason that players come to the "Main Fallback-Sawn" so often?

- a game-quit
- ~~a game-stop~~ plugin deactivation
- the player is not allowed to enter the game
- after rejoining the server within the "Lobby Area" / "Arena Area"

Maybe we can create another location for some cases to differentiate between the teleport reasons.

**Comment by pjindras** [comment]
in my case, every game quit and than sometimes server join / rejoin while no game is active

but quit location is set correctly

**Comment by pjindras** [comment]
> Or which case is the reason that players come to the "Main Fallback-Sawn" so often?
> 
> * a game-quit
> * ~a game-stop~ plugin deactivation
> * the player is not allowed to enter the game
> * after rejoining the server within the "Lobby Area" / "Arena Area"
> 
> Maybe we can create another location for some cases to differentiate between the teleport reasons.

The most after rejoining the game, which was left in lobby stage (before the game started)

**Comment by RedstoneFuture** [comment]
The [fallback spawn](https://github.com/RedstoneFuture/missilewars/wiki/Commands-and-Permissions#location-types) must not be inside the lobby. Otherwise, you cannot “enter the lobby” and checks will not be performed by the plugin. This is currently desired. And therefore not a bug.

When a new game starts, the player is teleported from the old game-area to the lobby in the `ENDGAME` phase. With the latest version, a game-join is also possible during the running game. This should allow you to configure the game so that the “fallback spawn” is only needed in an unexpected situation.
