### ISSUE TITLE
Equalize the game

### ISSUE THREAD

**Issue by AlloryDante** [Butzlabben/missilewars#62]
Hello, can you please somehow add an option that if there is an unequal game for ex 2v1, have a option to lower the time it takes until you generate an item.2v1 is very hard as the oponents gets double the items.

**Comment by RedstoneFuture** [comment]
It sounds like the requested feature has already been implemented:
https://github.com/Butzlabben/missilewars/wiki/Equipment-Interval

It's not only for unequal games, but you can change the equipment time by player x time. It may be enought, because e.g. 20 vs. 21 is unequal, but it's not a problem.

What do you think?

**Comment by RedstoneFuture** [comment]
Any response?

**Comment by daniel-naegele** [comment]
Close as feature is implemented.
